#! /bin/sh

bash ~/.config/polybar/launch.sh &
bash picom &

color0=#1984B5
color4=#373B41

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12

bspc config focused_border_color "$color0"
bspc config normal_border_color "$color4"
bspc config active_border_color "$color0"
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Thunar desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Auto-start
picom --config "$HOME/.config/bspwm/picom.conf" &
# nitrogen --set-auto "$HOME/.config/backgrounds/cheatsheet-debian.png" &
sh ~/.fehbg &


# Move to desktop
bspc desktop -f 1

